--------------------------------------------------------
--  DDL for Table TTRIPS
--------------------------------------------------------

  CREATE TABLE "TTRIPS" 
   (	"DESTINATION" VARCHAR2(255 BYTE), 
	"PRICE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ALUMNOS" ;
/
REM INSERTING into TTRIPS
SET DEFINE OFF;
INSERT INTO TTRIPS VALUES('LONDON', 450);
INSERT INTO TTRIPS VALUES('PARIS', 320);
INSERT INTO TTRIPS VALUES('ROME', 280);

COMMIT;
